### ISSUE TITLE
What is the reason for removing license and authors attribution in this derivative work?

### ISSUE THREAD

**Issue by kkm000** [datemoon/ASR-decoder#3]
https://github.com/datemoon/ASR-decoder/blob/8fd2ef0f53e73a76fdb6551ac087f30f3dcfb6b5/src/util/config-parse-options.h#L1-L6

The source this code is based on (latest change before the stated date of your "autorship"): https://github.com/kaldi-asr/kaldi/blob/afdfcbc6e95f7ee5bd33c988d850de41c4892225/src/util/parse-options.h

Apache 2.0 is very permissive, but not that permissive as to allow un-licensing. 
```
      "Derivative Works" shall mean any work, whether in Source or Object
      form, that is based on (or derived from) the Work and for which the
      editorial revisions, annotations, elaborations, or other modifications
      represent, as a whole, an original work of authorship. [...]
```
So this is clearly a derivative work.
```
   4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

      (a) You must give any other recipients of the Work or
          Derivative Works a copy of this License; and

      (b) You must cause any modified files to carry prominent notices
          stating that You changed the files; and

      (c) You must retain, in the Source form of any Derivative Works
          that You distribute, all copyright, patent, trademark, and
          attribution notices from the Source form of the Work,
          excluding those notices that do not pertain to any part of
          the Derivative Works[...]
```
Nobody will be likely be going after you (this is up to individual authors listed in the original file), but taking someone else's work and removing attribution is academically unethical, not "only" illegal.

Also, the README is misleading:

> it's ASR decoder and make graph project if you want compiler arm , you can use command "ARM=true make". linux command is "make"

This is not true for general public, nobody can, except you, as the code has no explicit license allowing anyone else to do so. Cloning or otherwise downloading the code from your repository without your written permission is illegal.

What's going on?

**Comment by datemoon** [comment]
Because my English is bad, so I'm not sure you can understand my mean.
 Because I need simple config read, so I delete some code .Thank you tell, I will add quote come from in up to date.
